def AcquisitionRecordMapping():
    return [('accession number', 'Accession Number'),
            ('summary', 'Description'),
            ('collection', 'Collection Title'),
            ('eadid', 'EADID'),
            ('type', 'Type'),
            ('prc', 'P/R/C'),
            ('restrictions', 'Restrictions'),
            ('restrictionComment', 'Restriction Comments'),
            ('totalPhysicalSize', 'totalPhysicalSize'),
            ('fileRecDate', 'Date Received'),
            ('donor', 'donor'),
            ('source', 'source'),
            ('origin', 'Origin'),
            ('adminNote', 'Administrative Comments'),
            ('existingDigitalCollection', 'Existing Digital Collection'),
            ('dasRecDate', 'DAS Date Received'),
            ('recLetter', 'Receipt Letter'),
            ('sendInv', 'Send Inventory to Donor'),
            ('giftAckOrDeed', 'Gift Acknowledgement or Deed of Gift'),
            ('access', 'Access'),
            ('recBy', 'Received By'),
            ('dasRecBy', 'DAS Received By'),
            ('addenda', 'Addenda'),
            ('physicalMedia', 'Physical Media'),
            ('existingPhysicalCollection', 'Existing Physical Collection'),
            ('physicalHasFindingAid', 'Physical Collection Has Finding Aid'),
            ('totalPhysicalSize', 'physSize'),
            ('sentToDASOn', 'Date sent to DAS'),
            ('spanDate', 'Span Date')
            ]
