def LDRFields():
    return [
            'accession number',
            'department',
            'summary',
            'fiscalYear',
            'ark',
            'collection',
            'eadid',
            'spanDate',
            'type',
            'prc',
            'rights',
            'restrictions',
            'totalDigitalSize',
            'digitalCondition',
            'fileInfo',
            'fileAccDate',
            'fileTransDate',
            'fileBackDate',
            'fileDelDate',
            'permittedUseAccess',
            'permittedUseDiscover',
            'existingDigitalCollection',
            'access',
            'addenda',
    ]
